server:
  servlet:
    encoding:
      charset: UTF-8

  # database ?? ??
      enabled: true
      force: true


spring:
  datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: org.mariadb.jdbc.Driver
    #    ?? PC? ????? Database??? ?? ???.
    #url: jdbc:mariadb://localhost:3307/mariadb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    url: jdbc:mariadb://localhost:3306/caffe

    #    mysql? ??? ??? ?? ??? ?? ???.
    username: root
    password: dkei380226
    #mariadb는 포트를 3307로했음
  thymeleaf:
    cache: false

  # spring data jpa ??
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create

  security:
    user:
      name: root
      password: 1234
      roles: ADMIN